version: '3.1'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ~/data/floweng/postgres:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - default
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ~/data/floweng/mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - default
    restart: always

networks:
  default:
